//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ContractTerms
    {
        public int ContractTermID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string Stage { get; set; }
        public string ExpectedDate { get; set; }
        public Nullable<int> ExpectedAmount { get; set; }
    }
}
