//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ExpenseReports
    {
        public int ExpenseReportID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> AssociateID { get; set; }
        public string ExpenseType { get; set; }
        public string ExpenseDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string Descr { get; set; }
    }
}
